/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.mediaAdmin;

import views.Admin.Sales.*;
import aims.FormatNumber;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import model.Media.Media;
import model.Media.PhysicalGood;
import model.Sale.MediaSale;
import model.Media.*;

/**
 *
 * @author hsnt
 */
public class MediaItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form MediaSaleItem
     */
    private Media media;
    public static final int WIDTH = 576;
    public static final int HEIGHT = 142;

    public MediaItemPanel(Media md) {
        setSize(WIDTH, HEIGHT);
        this.media = md;
        initComponents();
        this.media = media;
        mediaTitle.setText(media.getTitle());
        categoryLabel.setText(media.getCategoryId() + "");
        valueLabel.setText(FormatNumber.formatString(media.getValue() + ""));
        valueLabel.setName(media.getValue() + "");
        priceLabel.setText(FormatNumber.formatString(media.getPrice() + ""));
        priceLabel.setName(media.getPrice() + "");
            
    } 
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mediaTitle = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        showButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mediaTitle.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        mediaTitle.setText("jLabel1");

        categoryLabel.setText("jLabel1");

        valueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valueLabel.setText("jLabel1");

        jLabel2.setText("(VND)");

        jLabel3.setText("Value: ");

        jLabel4.setText("Price: ");

        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceLabel.setText("jLabel5");

        jLabel5.setText("(VND)");

        showButton.setText("Show");
        showButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showButton.setFocusPainted(false);

        deleteButton.setText("Delete");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setFocusPainted(false);

        editButton.setText("Edit");
        editButton.setFocusPainted(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Category : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mediaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(categoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45)
                                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(editButton)
                        .addGap(81, 81, 81)
                        .addComponent(showButton)
                        .addGap(69, 69, 69)
                        .addComponent(deleteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediaTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryLabel)
                            .addComponent(jLabel1))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valueLabel)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(priceLabel)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editButton)
                    .addComponent(deleteButton)
                    .addComponent(showButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        int category_id = media.getCategoryId();
//        System.out.println(category_id);
        JDialog jDialog1 = new JDialog();
        
        
        
        switch (category_id) {
            case 1:
                Book book = (Book) media;
                EditBookPanel book_edit_panel = new EditBookPanel(media);
                jDialog1.setSize(600, 550);
                book_edit_panel.setBounds(0,0,600,550);
                
                jDialog1.add(book_edit_panel);
                book_edit_panel.getExitButton().addActionListener((ActionEvent ae) -> {
                    jDialog1.dispose();
                });
                break;
            case 2:
                DVD dvd = (DVD) media;
                JPanel dvd_edit_panel = new EditDvdPanel();
                dvd_edit_panel.setVisible(true);
                
                break;
            case 3:
                CD cd = (CD) media;
                break;
            case 4:
                LP lp = (LP) media;
                break;
        }
        jDialog1.setUndecorated(true);
        jDialog1.setLocationRelativeTo(null);
        jDialog1.setModal(true);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed
    private int getValueNumber(JTextField textField) {
        try {
            int value = Integer.parseInt(textField.getText());
            return value;
        } catch (NumberFormatException e) {
            return -1;
        }
    }

//    private void changeSaleoff() {
//        precentLabel.addFocusListener(new FocusListener() {
//            @Override
//            public void focusGained(FocusEvent e) {
//
//            }
//
//            @Override
//            public void focusLost(FocusEvent e) {
//                int precent = getPrecent();
//                if (precent == 0) {
//
//                } else if (precent == -1 || precent < 30 || precent > 150) {
//                    precentLabel.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
//                } else {
//                    precentLabel.setBorder(BorderFactory.createLineBorder(Color.GREEN, 2));
//                    newPriceLabel.setText(FormatNumber.formatString("" + (media.getValue() * precent)));
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mediaTitle;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton showButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
