/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.mediaAdmin;

import views.Admin.Sales.*;
import aims.DateService;
import aims.FormatNumber;
import controller.Sale.SalesController;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import model.Media.Media;
import model.Sale.MediaSale;

/**
 *
 * @author hsnt
 */
public class MediaPanel extends javax.swing.JPanel {

    /**
     * Creates new form MediaSalePanel
     */
    public static int WIDTH = 788;
    public static int HEIGHT = 637;
    private List<MediaItemPanel> mediaItemPanels;
    private List<Media> medias;
    private MediaAddFrame media_frame;
    public MediaPanel(List<Media> medias) {
        initComponents();
        setSize(WIDTH, HEIGHT);
        this.medias = new ArrayList<Media>();
        this.medias = medias;
        MediaList mediaList = new MediaList(medias);
        mediaList.setBounds(40, 80, mediaList.getWidth(), mediaList.getHeight());
        mediaItemPanels = mediaList.getMediaItemPanels();     
        add(mediaList);
    }
    
    
    public List<Media> getMedias(){
        return medias;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(788, 633));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Media List");
        add(jLabel1);
        jLabel1.setBounds(330, 12, 170, 24);

        add_button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        add(add_button);
        add_button.setBounds(670, 40, 79, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        media_frame = new MediaAddFrame();
        media_frame.setLocationRelativeTo(null);
        media_frame.setVisible(true);
    }//GEN-LAST:event_add_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
