/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.account.UserPanel;

import static aims.AIMS.account;
import java.awt.BorderLayout;
import java.util.List;
import model.Cart.ShippingInfo;
import model.User.User;
import views.cart.ShippingList;
import views.cart.ShippingPanel;

/**
 *
 * @author thanhhff
 */
public class AccountInformation extends javax.swing.JPanel {

    /**
     * Creates new form AccountInformation
     */
    public AccountInformation() {
        initComponents();
//        
//        int user_id = account.getId();
        

        Username.setText("Username: " + account.getUsername());
        
        String accType = "null";
        if (account.getLv() == 0){
            accType = "User";
        } else if (account.getLv() == 1)
        {
            accType = "Admin";
        }
        
        AccountType.setText("Account Type: " + accType);
        
        // Get Shipping Infor
        
        User user = new User(account.getId());
//        ShippingPanel shippingPanel = new ShippingPanel(user);
//        
//        ShippingInfor.removeAll();
//        ShippingInfor.setLayout(new BorderLayout());
//        ShippingInfor.add(shippingPanel);
//        ShippingInfor.updateUI();

           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        AccountType = new javax.swing.JLabel();
        ShippingInfor = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        Username.setText("Username: ");

        AccountType.setText("Account Type:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountType)
                    .addComponent(Username))
                .addContainerGap(433, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Username)
                .addGap(18, 18, 18)
                .addComponent(AccountType)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        ShippingInfor.setBorder(javax.swing.BorderFactory.createTitledBorder("Shipping Information"));

        javax.swing.GroupLayout ShippingInforLayout = new javax.swing.GroupLayout(ShippingInfor);
        ShippingInfor.setLayout(ShippingInforLayout);
        ShippingInforLayout.setHorizontalGroup(
            ShippingInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ShippingInforLayout.setVerticalGroup(
            ShippingInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShippingInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(ShippingInfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountType;
    private javax.swing.JPanel ShippingInfor;
    private javax.swing.JLabel Username;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
