/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Admin.Sales;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import model.Sale.Sale;

/**
 *
 * @author hsnt
 */
public class SaleListPanel extends javax.swing.JPanel {

    /**
     * Creates new form S
     */
    private  JTable  table;
    private List<Sale> sales;
    public SaleListPanel(List<Sale> sales) {
        initComponents();
        this.sales = sales;
        String[] columnName = {"Sale_ID","Start_day","End_day","State"};
        int j = 4;
        int i = sales.size();
        Object [][] data = new Object[i][j];
        int index = 0;
        for(Sale sale : sales ){
            data[index][0] = sale.getSale_id();
            data[index][1] = sale.getStart_day();
            data[index][3] = sale.getState();
            data[index++][2] = sale.getEnd_day();
        }
        table = new JTable(data,columnName);
        JScrollPane scrollPane = new JScrollPane(table);
        table.setFillsViewportHeight(true);
        table.setBounds(12, 12 + 30, 630, 450);
        add(table.getTableHeader());
        add(table);
        table.getTableHeader().setBounds(12, 12, 630, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detail = new javax.swing.JButton();

        detail.setText("Detail");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(661, 661, 661)
                .addComponent(detail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detail)
                .addContainerGap(445, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        
        int row = table.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select sale");
        }else{
            JDialog jDialog = new JDialog();
            jDialog.setSize(500 + 12 + 12 , 450 + 30 + 12 + 12);
            jDialog.setUndecorated(true);
            jDialog.setLocationRelativeTo(null);
            SaleDetailPanel saleDetailPanel = new SaleDetailPanel(this.sales.get(row));
            jDialog.add(saleDetailPanel);
            saleDetailPanel.getOk().addActionListener((ActionEvent e) -> {
                jDialog.dispose();
            });
            jDialog.setVisible(true);
        }
    }//GEN-LAST:event_detailActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detail;
    // End of variables declaration//GEN-END:variables
}
