/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Admin.Sales;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import model.Media.Media;
import model.Sale.MediaSale;
import model.Sale.Sale;

/**
 *
 * @author hsnt
 */
public class SaleDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form MediaSaleList
     */
    public SaleDetailPanel(Sale sale) {
        initComponents();
        String[] columnName = {"Media name","Quantity sale","Percent"};
        int j = 3;
        List<MediaSale> mediaSales = sale.getMediaSales();
        int i = mediaSales.size();
        Object [][] data = new Object[i][j];
        int index = 0;
        for(MediaSale mediaSale : mediaSales){
            data[index][0] = Media.getTitlebyID(mediaSale.getMedia_id());
            data[index][1] = mediaSale.getQuantity();
            data[index++][2] = mediaSale.getPercent() + "%";
        }
        JTable table = new JTable(data,columnName);
        JScrollPane scrollPane = new JScrollPane(table);
        table.setFillsViewportHeight(true);
        table.setBounds(12, 12 + 30, 500, 350);
        add(table.getTableHeader());
        add(table);
        table.getTableHeader().setBounds(12, 12, 500, 30);
    }

    public JButton getOk() {
        return ok;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(524, 500));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(ok)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
