/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.MediaList;

import controller.Search.SearchController;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import model.Media.Media;

/**
 *
 * @author User
 */
public class mediaListPanel extends javax.swing.JPanel {

    /**
     * Creates new form categoryPanel
     */
    public mediaListPanel() {
        initComponents();
        //setLayout(null);
        fill();
    }
     public mediaListPanel(String search) {
        initComponents();
        //setLayout(null);
        fill(search);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void fill()
    {
        ArrayList<Media> list = new ArrayList<Media>();
        SearchController.SearchRandom(list);
        mediaList media = new mediaList(list);
        mediaListPanel.setLayout(new BorderLayout());
        mediaListPanel.add(media, BorderLayout.CENTER);
        mediaListPanel.updateUI();
    }
    public void fill(String search)
    {
        ArrayList<Media> list = new ArrayList<Media>();
        SearchController.SearchUser(list,search);
        mediaList media = new mediaList(list);
        mediaListPanel.setLayout(new BorderLayout());
        mediaListPanel.add(media, BorderLayout.CENTER);
        mediaListPanel.updateUI();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mediaListPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        book = new javax.swing.JButton();
        cd = new javax.swing.JButton();
        dvd = new javax.swing.JButton();
        lp = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Category");

        javax.swing.GroupLayout mediaListPanelLayout = new javax.swing.GroupLayout(mediaListPanel);
        mediaListPanel.setLayout(mediaListPanelLayout);
        mediaListPanelLayout.setHorizontalGroup(
            mediaListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        mediaListPanelLayout.setVerticalGroup(
            mediaListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        book.setText("Book");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        cd.setText("CD");
        cd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdActionPerformed(evt);
            }
        });

        dvd.setText("DVD");
        dvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvdActionPerformed(evt);
            }
        });

        lp.setText("LP");
        lp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dvd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(book, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(lp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(book)
                .addGap(60, 60, 60)
                .addComponent(cd)
                .addGap(59, 59, 59)
                .addComponent(dvd)
                .addGap(59, 59, 59)
                .addComponent(lp)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(mediaListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(mediaListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
        mediaListPanel.removeAll();
        ArrayList<Media> list = new ArrayList<Media>();
        SearchController.SearchBook(list);
        mediaList media = new mediaList(list);
        mediaListPanel.setLayout(new BorderLayout());
        mediaListPanel.add(media, BorderLayout.CENTER);
        mediaListPanel.updateUI();
    }//GEN-LAST:event_bookActionPerformed

    private void cdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdActionPerformed
        // TODO add your handling code here:
        mediaListPanel.removeAll();
        ArrayList<Media> list = new ArrayList<Media>();
        SearchController.SearchCd(list);
        mediaList media = new mediaList(list);
        mediaListPanel.setLayout(new BorderLayout());
        mediaListPanel.add(media, BorderLayout.CENTER);
        mediaListPanel.updateUI();
    }//GEN-LAST:event_cdActionPerformed

    private void dvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvdActionPerformed
        // TODO add your handling code here:
        mediaListPanel.removeAll();
        ArrayList<Media> list = new ArrayList<Media>();
        SearchController.SearchDvd(list);
        mediaList media = new mediaList(list);
        mediaListPanel.setLayout(new BorderLayout());
        mediaListPanel.add(media, BorderLayout.CENTER);
        mediaListPanel.updateUI();
    }//GEN-LAST:event_dvdActionPerformed

    private void jButton5bookrformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void lpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpActionPerformed
        // TODO add your handling code here:
        mediaListPanel.removeAll();
        ArrayList<Media> list = new ArrayList<Media>();
        SearchController.SearchLp(list);
        mediaList media = new mediaList(list);
        mediaListPanel.setLayout(new BorderLayout());
        mediaListPanel.add(media, BorderLayout.CENTER);
        mediaListPanel.updateUI();
    }//GEN-LAST:event_lpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book;
    private javax.swing.JButton cd;
    private javax.swing.JButton dvd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lp;
    private javax.swing.JPanel mediaListPanel;
    // End of variables declaration//GEN-END:variables
}
