/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.order;

import aims.FormatNumber;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import model.Cart.Order;

/**
 *
 * @author hsnt
 */
public class OrderListPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderListPanel
     */
    private JTable table;
    private List<Order> orders;
    public OrderListPanel(List<Order> orders) {
        this.orders = orders;
        setLayout(null);
        initComponents();
        String[] columnName = {"Order date","Total bill","Status"};
        int i = orders.size();
        int j = 3;
        Object [][] data = new Object[i][j];
        int index = 0;
        int totalall = 0;
        for(Order order: orders){
            data[index][0] = order.getCreated_at();
            totalall +=  order.getShip_fee()+ order.getTotalBill();
            data[index][1] = FormatNumber.formatString("" + (order.getShip_fee()+ order.getTotalBill())) + " VND";
            data[index++][2] = order.getState();
        }
        totalOrder.setText("" + index);
        totalAllBill.setText(FormatNumber.formatString("" + totalall) + " VND");
        table = new JTable(data,columnName);
        JScrollPane scrollPane = new JScrollPane(table);
        table.setFillsViewportHeight(true);
        table.setBounds(18, 12 + 32, 590, 305-35);
        add(table);
        add(table.getTableHeader());
        table.getTableHeader().setBounds(18, 12, 590, 32);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalOrder = new javax.swing.JLabel();
        totalAllBill = new javax.swing.JLabel();

        jButton1.setText("Order detail");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.setFocusPainted(false);

        jLabel1.setText("Total number of order: ");

        jLabel2.setText("Total all bill:");

        totalOrder.setText("jLabel3");

        totalAllBill.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalAllBill.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(613, 613, 613)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalOrder)
                            .addComponent(totalAllBill, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(241, 241, 241)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalOrder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalAllBill))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select order");
        }else{
            JDialog jDialog = new JDialog();
            jDialog.setSize(600, 562);
            OrderDetail orderDetail = new OrderDetail(orders.get(row));
            orderDetail.setBounds(0, 0, 600, 562);
            jDialog.setUndecorated(true);
            jDialog.add(orderDetail);
            jDialog.setLocationRelativeTo(null);
            orderDetail.getOkButton().addActionListener((ActionEvent e) -> {
                jDialog.dispose();
            });
            jDialog.setVisible(true);
         }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel totalAllBill;
    private javax.swing.JLabel totalOrder;
    // End of variables declaration//GEN-END:variables
}
