/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.order;

import aims.FormatNumber;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;
import model.Cart.Order;

/**
 *
 * @author hsnt
 */
public class OrderDetalPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderDetalPanel
     * @param order
     */
    public static int WIDTH = 570;
    public static int HEIGHT = 330;
    private JPanel mainJPanel = new JPanel();
    public OrderDetalPanel(Order order) {
        setSize(WIDTH,HEIGHT);
        initComponents();
        totalBillPanel.setText(FormatNumber.formatString("" + order.getTotalBill()));
        shipping_feePanel.setText(FormatNumber.formatString("" + order.getShip_fee()));
        totalPanel.setText(FormatNumber.formatString("" + (order.getTotalBill() + order.getShip_fee())));
        if(order.getOrder_state_id() != Order.DELIVERING){
            refundButton.setVisible(false);
        }
        switch(order.getOrder_state_id()){
            case Order.CANCEL:
                statePanel.setForeground(Color.RED);
                break;
            case Order.SUCCESS:
                statePanel.setForeground(Color.GREEN);
                break;
            case Order.DELIVERING:
                statePanel.setForeground(Color.YELLOW);
                break;
        }
        statePanel.setText(order.getState());
        mainJPanel.setBounds(12, 12, OrderMediaDetailListPanel.WIDTH, OrderMediaDetailListPanel.HEIGHT);
        mainJPanel.add(new OrderMediaDetailListPanel(order.getOrderItems()));
        add(mainJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalBillPanel = new javax.swing.JLabel();
        shipping_feePanel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalPanel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        statePanel = new javax.swing.JLabel();
        refundButton = new javax.swing.JButton();

        jLabel10.setText("jLabel10");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Total Bill: ");

        jLabel2.setText("Shipping Fee:");

        totalBillPanel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalBillPanel.setText("jLabel3");

        shipping_feePanel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shipping_feePanel.setText("jLabel4");

        jLabel5.setText("VND");

        jLabel6.setText("VND");

        jLabel7.setText("Total : ");

        totalPanel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        totalPanel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPanel.setText("jLabel8");

        jLabel9.setText("VND");

        jLabel11.setText("State: ");

        statePanel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        statePanel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statePanel.setText("jLabel12");

        refundButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/money-back.png"))); // NOI18N
        refundButton.setBorderPainted(false);
        refundButton.setContentAreaFilled(false);
        refundButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refundButton.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalBillPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(shipping_feePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(refundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(totalBillPanel)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(totalPanel)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(shipping_feePanel)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(statePanel)))
                    .addComponent(refundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton refundButton;
    private javax.swing.JLabel shipping_feePanel;
    private javax.swing.JLabel statePanel;
    private javax.swing.JLabel totalBillPanel;
    private javax.swing.JLabel totalPanel;
    // End of variables declaration//GEN-END:variables
}
