/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Admin.User;

import controller.User.UserController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User.Account;

/**
 *
 * @author thanhhff
 */
public class UserPanel extends javax.swing.JPanel {
    UserController userAccount = new UserController();
    /**
     * Creates new form User
     */
    public UserPanel() {
        initComponents();
        FillTable();
    }
    
    public void FillTable()
    {
        ArrayList<Account> arrAccount = userAccount.getListAccount();
        DefaultTableModel tbmodel = new DefaultTableModel();
        
        tbmodel.addColumn("ID");
        tbmodel.addColumn("Username");
        tbmodel.addColumn("Account Status");
        
        if (arrAccount != null)
        {
            int accountNumber = 0;
            for (Account acc : arrAccount){
                accountNumber += 1;
                
                String lvStatus = "";
                
                if (acc.getLv() == 0){
                    lvStatus = "User";
                } else if (acc.getLv() == 1){
                    lvStatus = "Admin";
                } else if (acc.getLv() == 2){
                    lvStatus = "Block";
                }
                tbmodel.addRow(new Object[]{acc.getId(), acc.getUsername(), lvStatus});
            }
            
            totalNumber.setText("Total number of accounts: " + String.valueOf(accountNumber));

        }
        
        
        tbAccount.setModel(tbmodel);
        
        for (int i = 0; i < tbAccount.getColumnCount(); i++) {
            Class<?> col = tbAccount.getColumnClass(i);
            tbAccount.setDefaultEditor(col, null);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAccount = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        totalNumber = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("User Account Manager"));
        setPreferredSize(new java.awt.Dimension(1099, 694));

        tbAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Username", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAccount);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Edit.setText("Edit");

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        totalNumber.setText("Total number of accounts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalNumber)
                        .addContainerGap(906, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalNumber)
                .addContainerGap(367, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
       
        int[] selectedRows = tbAccount.getSelectedRows();
        
        if (selectedRows.length <= 0) {
            JOptionPane.showMessageDialog(null, "You are not select row!");
        } else {
            ArrayList<Integer> ListAccount = new ArrayList<Integer>();
            String sp = "";
            
             for (int i : selectedRows) {
                int ma = (int) tbAccount.getValueAt(i, 0);
                ListAccount.add(ma);
                String userName = (String) tbAccount.getValueAt(i, 1);
                sp += userName + "\n";
            }
            int qs;
            qs = JOptionPane.showConfirmDialog(null, "Delete this account:\n " + sp, "Delete Account", JOptionPane.YES_NO_OPTION);
            if (qs == JOptionPane.YES_OPTION) {
                boolean delete = userAccount.deleteAccount(ListAccount);
                if (delete == true) {
                    FillTable();
                } else
                    JOptionPane.showMessageDialog(null, "Can not delete this account!");

            }
        }
    }//GEN-LAST:event_RemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Remove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAccount;
    private javax.swing.JLabel totalNumber;
    // End of variables declaration//GEN-END:variables
}
