/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.cart;

import javax.swing.JButton;
import model.Cart.ShippingInfo;
import model.Cart.Ward;
import model.User.User;

/**
 *
 * @author thanhhff
 */
public class ChangeAddress extends javax.swing.JPanel {

    /**
     * Creates new form ChangeAddress
     */
    private boolean flag_province = false;
    private boolean flag_district = false;
    private User user;
    public static final int WIDTH = 500;
    public static final int HEIGHT = 450;

    public ChangeAddress(User user) {
        this.user = user;
        initComponents();
        submitButton.setFocusPainted(false);
        cancelButton.setFocusPainted(false);
        setProvince();
        setDistrict(provinceBox.getSelectedItem().toString());
        setWard(districtBox.getSelectedItem().toString());
    }

    public String getNameNew() {
        return nameText.getText();
    }

    public String getPhoneNew() {
        return phoneText.getText();
    }

    public JButton getCancelButton() {
        return this.cancelButton;
    }

    public ShippingInfo getShippingInfo() {
        String name = getNameNew();
        String phone = getPhoneNew();
        Ward ward = Ward.getWardbyName(wardBox.getSelectedItem().toString());
        ShippingInfo shippingInfo = new ShippingInfo(name, phone, user.getUser_id(), ward);
        return shippingInfo;
    }

    public JButton getSubmitButton() {
        return this.submitButton;
    }

    private void setProvince() {
        flag_province = false;
        for (String name : ShippingInfo.getProvinces()) {
            provinceBox.addItem(name);
        }
        flag_province = true;
    }

    private void setDistrict(String province) {

        flag_district = false;

        districtBox.removeAllItems();
        for (String name : ShippingInfo.getDistricts(province)) {
            districtBox.addItem(name);
        }
        flag_district = true;

    }

    private void setWard(String district) {

        wardBox.removeAllItems();
        for (String name : ShippingInfo.getWards(district)) {
            wardBox.addItem(name);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        provinceBox = new javax.swing.JComboBox<>();
        districtBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        wardBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 450));

        jLabel1.setText("Name");

        jLabel2.setText("Phone");

        phoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Province");

        jLabel4.setText("Districts");

        submitButton.setText("Submit");

        cancelButton.setText("Cancel");

        provinceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceBoxActionPerformed(evt);
            }
        });

        districtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Ward");

        wardBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Shipping Infomation New");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(62, 62, 62)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nameText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phoneText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(provinceBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 297, Short.MAX_VALUE)
                        .addComponent(districtBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wardBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(provinceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(districtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wardBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void provinceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceBoxActionPerformed
        if (flag_province) {
            setDistrict(provinceBox.getSelectedItem().toString());
            setWard(districtBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_provinceBoxActionPerformed

    private void phoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextActionPerformed

    private void wardBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardBoxActionPerformed

    }//GEN-LAST:event_wardBoxActionPerformed

    private void districtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtBoxActionPerformed
        // TODO add your handling code here:
        if (flag_district) {
            setWard(districtBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_districtBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> districtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField phoneText;
    private javax.swing.JComboBox<String> provinceBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox<String> wardBox;
    // End of variables declaration//GEN-END:variables
}
