/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.cart;

import javax.swing.JRadioButton;
import model.Cart.ShippingInfo;

/**
 *
 * @author hsnt
 */
public class ShippingInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form Shipping
     */
    public static final int WIDTH = 400;
    public static final int HEIGHT = 80;
    private ShippingInfo shippingInfo;
    public ShippingInfoPanel(ShippingInfo shippingInfo) {
        initComponents();
        this.shippingInfo = shippingInfo;
        namePhoneLabel.setText(shippingInfo.getName() + " - " + shippingInfo.getPhone());
        addressLabel.setText(shippingInfo.getWardObject().getWard() + "-" + shippingInfo.getWardObject().getDistrict() + "-" + shippingInfo.getWardObject().getProvince());
        setSize(WIDTH,500);
    } 

    public ShippingInfo getShippingInfo() {
        return shippingInfo;
    }

    
    public String getNamePhone(){
        return namePhoneLabel.getText();
    }
    public String getProvince(){
        return addressLabel.getText().split("-")[2];
    }
    public String getDistrict(){
        return addressLabel.getText().split("-")[1];
    }
    public String getWard(){
        return addressLabel.getText().split("-")[0];
    }
    public JRadioButton getRadioButton(){
        return this.namePhoneLabel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePhoneLabel = new javax.swing.JRadioButton();
        addressLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        namePhoneLabel.setText("Name - Phone ");
        namePhoneLabel.setFocusPainted(false);
        namePhoneLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namePhoneLabelActionPerformed(evt);
            }
        });

        addressLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(namePhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namePhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void namePhoneLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namePhoneLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namePhoneLabelActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        namePhoneLabel.setSelected(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JRadioButton namePhoneLabel;
    // End of variables declaration//GEN-END:variables
}
